### PR TITLE
Update ci.yml to use metacity

### PR DESCRIPTION
**Pull request by LorenzoBettini**
This installs metacity and other requirements to let the Maven build find a proper Window Manager for UI tests

### CODE REVIEW

**Comment by LorenzoBettini** [comment]
@PatrickTasse let's see if this fixes the failed tests

**Comment by LorenzoBettini** [comment]
@PatrickTasse the build still fails but with this PR it passes the critical test that used to fail before.
This time, the failure is due to 

```
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.IllegalArgumentException: EN.keyboard not found, see http://wiki.eclipse.org/SWTBot/Keyboard_Layouts for more information. [in thread "test"]
```

At least, this seems one of the main errors.

Do you know if SWTBot requires specific settings from the underlying OS?

**Comment by LorenzoBettini** [comment]
@PatrickTasse your suggestion fixed those tests, but there's another one (actually, it was there before, but I didn't notice that):

```
Errors: 
  MenuDetectTest.testMenuDetect:129 » SWT Failed to execute runnable (java.lang.AssertionError: SWT.MenuDetect not inside bounds. Position: Point {0, 0} bounds: Rectangle {0, 0, 0, 1})
```

**Comment by PatrickTasse** [comment]
That is very strange. From the stack trace we can see it happens while invoking the context menu on the label, but its bounds are {0, 0, 0, 1}. Locally for me they are {0, 0, 250, 750}. And in the build artifacts we can see that the screenshot looks normal and that the label is the expected size. And we know it's using the right label because another label would not have the listener that performs the bounds check.

**Comment by LorenzoBettini** [comment]
@PatrickTasse I'm not familiar with that code, but could it be due to the window taking the whole screen and so the coordinates are like that?

**Comment by PatrickTasse** [comment]
I suspected that perhaps the test was running too early before the shell and widgets have computed their layout. So I added a new widget condition to wait for the widget to have not empty bounds. It seems to solve the problem.

It went further and it exposed all the other tests that need the keyboard layout to be set. I have updated your commit and added another one for the MenuDetectTest label bounds issue.

Could you please update your commit according to the one found in this draft:
https://github.com/eclipse-swtbot/org.eclipse.swtbot/pull/4/commits

I'm curious to see if the MenuDetectTest will still fail with this change, before we try to add the last fix.

I'm not sure about the way of working to update someone else's commit and PR in github...

**Comment by LorenzoBettini** [comment]
@PatrickTasse glad you fixed the failing tests :)

Since your PR is built on top of my branch with my commits I suggest you to merge directly your PR and we close this one.

**Comment by PatrickTasse** [comment]
@LorenzoBettini It seems that the MenuDetectTest works without the fix. Perhaps it was the keyboard failures that left the build machine in a bad state and caused the later failures.

I tried to update your branch just to amend the last commit, let's see if if works.

**Review by PatrickTasse — APPROVED** [review]

**Comment by LorenzoBettini** [comment]
Looks like it's working. Shall we rebase and merge? I'd avoid squashing.

**Pull request merged**
